// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://zeegjxopcbgnhpwxcovo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InplZWdqeG9wY2Jnbmhwd3hjb3ZvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjE0NzUwMzcsImV4cCI6MjA3NzA1MTAzN30.1vPovNvUMSmxKpMg3pgmSyaGqNfz1R70tyZUWsScrTg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);